/**
 * THIS FILE IS AUTO-GENERATED.
 * DO NOT MODIFY IT MANUALLY.
 */

import type { AccessorPairs } from '../eslint/accessor-pairs.js';
import type { ArrayBracketNewline } from '../eslint/array-bracket-newline.js';
import type { ArrayBracketSpacing } from '../eslint/array-bracket-spacing.js';
import type { ArrayCallbackReturn } from '../eslint/array-callback-return.js';
import type { ArrayElementNewline } from '../eslint/array-element-newline.js';
import type { ArrowBodyStyle } from '../eslint/arrow-body-style.js';
import type { ArrowParens } from '../eslint/arrow-parens.js';
import type { ArrowSpacing } from '../eslint/arrow-spacing.js';
import type { BlockScopedVar } from '../eslint/block-scoped-var.js';
import type { BlockSpacing } from '../eslint/block-spacing.js';
import type { BraceStyle } from '../eslint/brace-style.js';
import type { Camelcase } from '../eslint/camelcase.js';
import type { CapitalizedComments } from '../eslint/capitalized-comments.js';
import type { ClassMethodsUseThis } from '../eslint/class-methods-use-this.js';
import type { CommaDangle } from '../eslint/comma-dangle.js';
import type { CommaSpacing } from '../eslint/comma-spacing.js';
import type { CommaStyle } from '../eslint/comma-style.js';
import type { Complexity } from '../eslint/complexity.js';
import type { ComputedPropertySpacing } from '../eslint/computed-property-spacing.js';
import type { ConsistentReturn } from '../eslint/consistent-return.js';
import type { ConsistentThis } from '../eslint/consistent-this.js';
import type { ConstructorSuper } from '../eslint/constructor-super.js';
import type { Curly } from '../eslint/curly.js';
import type { DefaultCase } from '../eslint/default-case.js';
import type { DefaultCaseLast } from '../eslint/default-case-last.js';
import type { DefaultParamLast } from '../eslint/default-param-last.js';
import type { DotLocation } from '../eslint/dot-location.js';
import type { DotNotation } from '../eslint/dot-notation.js';
import type { EolLast } from '../eslint/eol-last.js';
import type { Eqeqeq } from '../eslint/eqeqeq.js';
import type { ForDirection } from '../eslint/for-direction.js';
import type { FuncCallSpacing } from '../eslint/func-call-spacing.js';
import type { FuncNameMatching } from '../eslint/func-name-matching.js';
import type { FuncNames } from '../eslint/func-names.js';
import type { FuncStyle } from '../eslint/func-style.js';
import type { FunctionCallArgumentNewline } from '../eslint/function-call-argument-newline.js';
import type { FunctionParenNewline } from '../eslint/function-paren-newline.js';
import type { GeneratorStarSpacing } from '../eslint/generator-star-spacing.js';
import type { GetterReturn } from '../eslint/getter-return.js';
import type { GroupedAccessorPairs } from '../eslint/grouped-accessor-pairs.js';
import type { GuardForIn } from '../eslint/guard-for-in.js';
import type { IdDenylist } from '../eslint/id-denylist.js';
import type { IdLength } from '../eslint/id-length.js';
import type { IdMatch } from '../eslint/id-match.js';
import type { ImplicitArrowLinebreak } from '../eslint/implicit-arrow-linebreak.js';
import type { Indent } from '../eslint/indent.js';
import type { InitDeclarations } from '../eslint/init-declarations.js';
import type { JsxQuotes } from '../eslint/jsx-quotes.js';
import type { KeySpacing } from '../eslint/key-spacing.js';
import type { KeywordSpacing } from '../eslint/keyword-spacing.js';
import type { LineCommentPosition } from '../eslint/line-comment-position.js';
import type { LinebreakStyle } from '../eslint/linebreak-style.js';
import type { LinesAroundComment } from '../eslint/lines-around-comment.js';
import type { LinesBetweenClassMembers } from '../eslint/lines-between-class-members.js';
import type { LogicalAssignmentOperators } from '../eslint/logical-assignment-operators.js';
import type { MaxClassesPerFile } from '../eslint/max-classes-per-file.js';
import type { MaxDepth } from '../eslint/max-depth.js';
import type { MaxLen } from '../eslint/max-len.js';
import type { MaxLines } from '../eslint/max-lines.js';
import type { MaxLinesPerFunction } from '../eslint/max-lines-per-function.js';
import type { MaxNestedCallbacks } from '../eslint/max-nested-callbacks.js';
import type { MaxParams } from '../eslint/max-params.js';
import type { MaxStatements } from '../eslint/max-statements.js';
import type { MaxStatementsPerLine } from '../eslint/max-statements-per-line.js';
import type { MultilineCommentStyle } from '../eslint/multiline-comment-style.js';
import type { MultilineTernary } from '../eslint/multiline-ternary.js';
import type { NewCap } from '../eslint/new-cap.js';
import type { NewParens } from '../eslint/new-parens.js';
import type { NewlinePerChainedCall } from '../eslint/newline-per-chained-call.js';
import type { NoAlert } from '../eslint/no-alert.js';
import type { NoArrayConstructor } from '../eslint/no-array-constructor.js';
import type { NoAsyncPromiseExecutor } from '../eslint/no-async-promise-executor.js';
import type { NoAwaitInLoop } from '../eslint/no-await-in-loop.js';
import type { NoBitwise } from '../eslint/no-bitwise.js';
import type { NoCaller } from '../eslint/no-caller.js';
import type { NoCaseDeclarations } from '../eslint/no-case-declarations.js';
import type { NoClassAssign } from '../eslint/no-class-assign.js';
import type { NoCompareNegZero } from '../eslint/no-compare-neg-zero.js';
import type { NoCondAssign } from '../eslint/no-cond-assign.js';
import type { NoConfusingArrow } from '../eslint/no-confusing-arrow.js';
import type { NoConsole } from '../eslint/no-console.js';
import type { NoConstAssign } from '../eslint/no-const-assign.js';
import type { NoConstantBinaryExpression } from '../eslint/no-constant-binary-expression.js';
import type { NoConstantCondition } from '../eslint/no-constant-condition.js';
import type { NoConstructorReturn } from '../eslint/no-constructor-return.js';
import type { NoContinue } from '../eslint/no-continue.js';
import type { NoControlRegex } from '../eslint/no-control-regex.js';
import type { NoDebugger } from '../eslint/no-debugger.js';
import type { NoDeleteVar } from '../eslint/no-delete-var.js';
import type { NoDivRegex } from '../eslint/no-div-regex.js';
import type { NoDupeArgs } from '../eslint/no-dupe-args.js';
import type { NoDupeClassMembers } from '../eslint/no-dupe-class-members.js';
import type { NoDupeElseIf } from '../eslint/no-dupe-else-if.js';
import type { NoDupeKeys } from '../eslint/no-dupe-keys.js';
import type { NoDuplicateCase } from '../eslint/no-duplicate-case.js';
import type { NoDuplicateImports } from '../eslint/no-duplicate-imports.js';
import type { NoElseReturn } from '../eslint/no-else-return.js';
import type { NoEmpty } from '../eslint/no-empty.js';
import type { NoEmptyCharacterClass } from '../eslint/no-empty-character-class.js';
import type { NoEmptyFunction } from '../eslint/no-empty-function.js';
import type { NoEmptyPattern } from '../eslint/no-empty-pattern.js';
import type { NoEmptyStaticBlock } from '../eslint/no-empty-static-block.js';
import type { NoEqNull } from '../eslint/no-eq-null.js';
import type { NoEval } from '../eslint/no-eval.js';
import type { NoExAssign } from '../eslint/no-ex-assign.js';
import type { NoExtendNative } from '../eslint/no-extend-native.js';
import type { NoExtraBind } from '../eslint/no-extra-bind.js';
import type { NoExtraBooleanCast } from '../eslint/no-extra-boolean-cast.js';
import type { NoExtraLabel } from '../eslint/no-extra-label.js';
import type { NoExtraParens } from '../eslint/no-extra-parens.js';
import type { NoExtraSemi } from '../eslint/no-extra-semi.js';
import type { NoFallthrough } from '../eslint/no-fallthrough.js';
import type { NoFloatingDecimal } from '../eslint/no-floating-decimal.js';
import type { NoFuncAssign } from '../eslint/no-func-assign.js';
import type { NoGlobalAssign } from '../eslint/no-global-assign.js';
import type { NoImplicitCoercion } from '../eslint/no-implicit-coercion.js';
import type { NoImplicitGlobals } from '../eslint/no-implicit-globals.js';
import type { NoImpliedEval } from '../eslint/no-implied-eval.js';
import type { NoImportAssign } from '../eslint/no-import-assign.js';
import type { NoInlineComments } from '../eslint/no-inline-comments.js';
import type { NoInnerDeclarations } from '../eslint/no-inner-declarations.js';
import type { NoInvalidRegexp } from '../eslint/no-invalid-regexp.js';
import type { NoInvalidThis } from '../eslint/no-invalid-this.js';
import type { NoIrregularWhitespace } from '../eslint/no-irregular-whitespace.js';
import type { NoIterator } from '../eslint/no-iterator.js';
import type { NoLabelVar } from '../eslint/no-label-var.js';
import type { NoLabels } from '../eslint/no-labels.js';
import type { NoLoneBlocks } from '../eslint/no-lone-blocks.js';
import type { NoLonelyIf } from '../eslint/no-lonely-if.js';
import type { NoLoopFunc } from '../eslint/no-loop-func.js';
import type { NoLossOfPrecision } from '../eslint/no-loss-of-precision.js';
import type { NoMagicNumbers } from '../eslint/no-magic-numbers.js';
import type { NoMisleadingCharacterClass } from '../eslint/no-misleading-character-class.js';
import type { NoMixedOperators } from '../eslint/no-mixed-operators.js';
import type { NoMixedSpacesAndTabs } from '../eslint/no-mixed-spaces-and-tabs.js';
import type { NoMultiAssign } from '../eslint/no-multi-assign.js';
import type { NoMultiSpaces } from '../eslint/no-multi-spaces.js';
import type { NoMultiStr } from '../eslint/no-multi-str.js';
import type { NoMultipleEmptyLines } from '../eslint/no-multiple-empty-lines.js';
import type { NoNegatedCondition } from '../eslint/no-negated-condition.js';
import type { NoNestedTernary } from '../eslint/no-nested-ternary.js';
import type { NoNew } from '../eslint/no-new.js';
import type { NoNewFunc } from '../eslint/no-new-func.js';
import type { NoNewNativeNonconstructor } from '../eslint/no-new-native-nonconstructor.js';
import type { NoNewObject } from '../eslint/no-new-object.js';
import type { NoNewSymbol } from '../eslint/no-new-symbol.js';
import type { NoNewWrappers } from '../eslint/no-new-wrappers.js';
import type { NoNonoctalDecimalEscape } from '../eslint/no-nonoctal-decimal-escape.js';
import type { NoObjCalls } from '../eslint/no-obj-calls.js';
import type { NoOctal } from '../eslint/no-octal.js';
import type { NoOctalEscape } from '../eslint/no-octal-escape.js';
import type { NoParamReassign } from '../eslint/no-param-reassign.js';
import type { NoPlusplus } from '../eslint/no-plusplus.js';
import type { NoPromiseExecutorReturn } from '../eslint/no-promise-executor-return.js';
import type { NoProto } from '../eslint/no-proto.js';
import type { NoPrototypeBuiltins } from '../eslint/no-prototype-builtins.js';
import type { NoRedeclare } from '../eslint/no-redeclare.js';
import type { NoRegexSpaces } from '../eslint/no-regex-spaces.js';
import type { NoRestrictedExports } from '../eslint/no-restricted-exports.js';
import type { NoRestrictedGlobals } from '../eslint/no-restricted-globals.js';
import type { NoRestrictedImports } from '../eslint/no-restricted-imports.js';
import type { NoRestrictedProperties } from '../eslint/no-restricted-properties.js';
import type { NoRestrictedSyntax } from '../eslint/no-restricted-syntax.js';
import type { NoReturnAssign } from '../eslint/no-return-assign.js';
import type { NoReturnAwait } from '../eslint/no-return-await.js';
import type { NoScriptUrl } from '../eslint/no-script-url.js';
import type { NoSelfAssign } from '../eslint/no-self-assign.js';
import type { NoSelfCompare } from '../eslint/no-self-compare.js';
import type { NoSequences } from '../eslint/no-sequences.js';
import type { NoSetterReturn } from '../eslint/no-setter-return.js';
import type { NoShadow } from '../eslint/no-shadow.js';
import type { NoShadowRestrictedNames } from '../eslint/no-shadow-restricted-names.js';
import type { NoSparseArrays } from '../eslint/no-sparse-arrays.js';
import type { NoTabs } from '../eslint/no-tabs.js';
import type { NoTemplateCurlyInString } from '../eslint/no-template-curly-in-string.js';
import type { NoTernary } from '../eslint/no-ternary.js';
import type { NoThisBeforeSuper } from '../eslint/no-this-before-super.js';
import type { NoThrowLiteral } from '../eslint/no-throw-literal.js';
import type { NoTrailingSpaces } from '../eslint/no-trailing-spaces.js';
import type { NoUndef } from '../eslint/no-undef.js';
import type { NoUndefInit } from '../eslint/no-undef-init.js';
import type { NoUndefined } from '../eslint/no-undefined.js';
import type { NoUnderscoreDangle } from '../eslint/no-underscore-dangle.js';
import type { NoUnexpectedMultiline } from '../eslint/no-unexpected-multiline.js';
import type { NoUnmodifiedLoopCondition } from '../eslint/no-unmodified-loop-condition.js';
import type { NoUnneededTernary } from '../eslint/no-unneeded-ternary.js';
import type { NoUnreachable } from '../eslint/no-unreachable.js';
import type { NoUnreachableLoop } from '../eslint/no-unreachable-loop.js';
import type { NoUnsafeFinally } from '../eslint/no-unsafe-finally.js';
import type { NoUnsafeNegation } from '../eslint/no-unsafe-negation.js';
import type { NoUnsafeOptionalChaining } from '../eslint/no-unsafe-optional-chaining.js';
import type { NoUnusedExpressions } from '../eslint/no-unused-expressions.js';
import type { NoUnusedLabels } from '../eslint/no-unused-labels.js';
import type { NoUnusedPrivateClassMembers } from '../eslint/no-unused-private-class-members.js';
import type { NoUnusedVars } from '../eslint/no-unused-vars.js';
import type { NoUseBeforeDefine } from '../eslint/no-use-before-define.js';
import type { NoUselessBackreference } from '../eslint/no-useless-backreference.js';
import type { NoUselessCall } from '../eslint/no-useless-call.js';
import type { NoUselessCatch } from '../eslint/no-useless-catch.js';
import type { NoUselessComputedKey } from '../eslint/no-useless-computed-key.js';
import type { NoUselessConcat } from '../eslint/no-useless-concat.js';
import type { NoUselessConstructor } from '../eslint/no-useless-constructor.js';
import type { NoUselessEscape } from '../eslint/no-useless-escape.js';
import type { NoUselessRename } from '../eslint/no-useless-rename.js';
import type { NoUselessReturn } from '../eslint/no-useless-return.js';
import type { NoVar } from '../eslint/no-var.js';
import type { NoVoid } from '../eslint/no-void.js';
import type { NoWarningComments } from '../eslint/no-warning-comments.js';
import type { NoWhitespaceBeforeProperty } from '../eslint/no-whitespace-before-property.js';
import type { NoWith } from '../eslint/no-with.js';
import type { NonblockStatementBodyPosition } from '../eslint/nonblock-statement-body-position.js';
import type { ObjectCurlyNewline } from '../eslint/object-curly-newline.js';
import type { ObjectCurlySpacing } from '../eslint/object-curly-spacing.js';
import type { ObjectPropertyNewline } from '../eslint/object-property-newline.js';
import type { ObjectShorthand } from '../eslint/object-shorthand.js';
import type { OneVar } from '../eslint/one-var.js';
import type { OneVarDeclarationPerLine } from '../eslint/one-var-declaration-per-line.js';
import type { OperatorAssignment } from '../eslint/operator-assignment.js';
import type { OperatorLinebreak } from '../eslint/operator-linebreak.js';
import type { PaddedBlocks } from '../eslint/padded-blocks.js';
import type { PaddingLineBetweenStatements } from '../eslint/padding-line-between-statements.js';
import type { PreferArrowCallback } from '../eslint/prefer-arrow-callback.js';
import type { PreferConst } from '../eslint/prefer-const.js';
import type { PreferDestructuring } from '../eslint/prefer-destructuring.js';
import type { PreferExponentiationOperator } from '../eslint/prefer-exponentiation-operator.js';
import type { PreferNamedCaptureGroup } from '../eslint/prefer-named-capture-group.js';
import type { PreferNumericLiterals } from '../eslint/prefer-numeric-literals.js';
import type { PreferObjectHasOwn } from '../eslint/prefer-object-has-own.js';
import type { PreferObjectSpread } from '../eslint/prefer-object-spread.js';
import type { PreferPromiseRejectErrors } from '../eslint/prefer-promise-reject-errors.js';
import type { PreferRegexLiterals } from '../eslint/prefer-regex-literals.js';
import type { PreferRestParams } from '../eslint/prefer-rest-params.js';
import type { PreferSpread } from '../eslint/prefer-spread.js';
import type { PreferTemplate } from '../eslint/prefer-template.js';
import type { QuoteProps } from '../eslint/quote-props.js';
import type { Quotes } from '../eslint/quotes.js';
import type { Radix } from '../eslint/radix.js';
import type { RequireAtomicUpdates } from '../eslint/require-atomic-updates.js';
import type { RequireAwait } from '../eslint/require-await.js';
import type { RequireUnicodeRegexp } from '../eslint/require-unicode-regexp.js';
import type { RequireYield } from '../eslint/require-yield.js';
import type { RestSpreadSpacing } from '../eslint/rest-spread-spacing.js';
import type { Semi } from '../eslint/semi.js';
import type { SemiSpacing } from '../eslint/semi-spacing.js';
import type { SemiStyle } from '../eslint/semi-style.js';
import type { SortImports } from '../eslint/sort-imports.js';
import type { SortKeys } from '../eslint/sort-keys.js';
import type { SortVars } from '../eslint/sort-vars.js';
import type { SpaceBeforeBlocks } from '../eslint/space-before-blocks.js';
import type { SpaceBeforeFunctionParen } from '../eslint/space-before-function-paren.js';
import type { SpaceInParens } from '../eslint/space-in-parens.js';
import type { SpaceInfixOps } from '../eslint/space-infix-ops.js';
import type { SpaceUnaryOps } from '../eslint/space-unary-ops.js';
import type { SpacedComment } from '../eslint/spaced-comment.js';
import type { Strict } from '../eslint/strict.js';
import type { SwitchColonSpacing } from '../eslint/switch-colon-spacing.js';
import type { SymbolDescription } from '../eslint/symbol-description.js';
import type { TemplateCurlySpacing } from '../eslint/template-curly-spacing.js';
import type { TemplateTagSpacing } from '../eslint/template-tag-spacing.js';
import type { UnicodeBom } from '../eslint/unicode-bom.js';
import type { UseIsnan } from '../eslint/use-isnan.js';
import type { ValidTypeof } from '../eslint/valid-typeof.js';
import type { VarsOnTop } from '../eslint/vars-on-top.js';
import type { WrapIife } from '../eslint/wrap-iife.js';
import type { WrapRegex } from '../eslint/wrap-regex.js';
import type { YieldStarSpacing } from '../eslint/yield-star-spacing.js';
import type { Yoda } from '../eslint/yoda.js';

/** `eslint` Rules */
export interface Eslint {
  'accessor-pairs': AccessorPairs;
  'array-bracket-newline': ArrayBracketNewline;
  'array-bracket-spacing': ArrayBracketSpacing;
  'array-callback-return': ArrayCallbackReturn;
  'array-element-newline': ArrayElementNewline;
  'arrow-body-style': ArrowBodyStyle;
  'arrow-parens': ArrowParens;
  'arrow-spacing': ArrowSpacing;
  'block-scoped-var': BlockScopedVar;
  'block-spacing': BlockSpacing;
  'brace-style': BraceStyle;
  camelcase: Camelcase;
  'capitalized-comments': CapitalizedComments;
  'class-methods-use-this': ClassMethodsUseThis;
  'comma-dangle': CommaDangle;
  'comma-spacing': CommaSpacing;
  'comma-style': CommaStyle;
  complexity: Complexity;
  'computed-property-spacing': ComputedPropertySpacing;
  'consistent-return': ConsistentReturn;
  'consistent-this': ConsistentThis;
  'constructor-super': ConstructorSuper;
  curly: Curly;
  'default-case': DefaultCase;
  'default-case-last': DefaultCaseLast;
  'default-param-last': DefaultParamLast;
  'dot-location': DotLocation;
  'dot-notation': DotNotation;
  'eol-last': EolLast;
  eqeqeq: Eqeqeq;
  'for-direction': ForDirection;
  'func-call-spacing': FuncCallSpacing;
  'func-name-matching': FuncNameMatching;
  'func-names': FuncNames;
  'func-style': FuncStyle;
  'function-call-argument-newline': FunctionCallArgumentNewline;
  'function-paren-newline': FunctionParenNewline;
  'generator-star-spacing': GeneratorStarSpacing;
  'getter-return': GetterReturn;
  'grouped-accessor-pairs': GroupedAccessorPairs;
  'guard-for-in': GuardForIn;
  'id-denylist': IdDenylist;
  'id-length': IdLength;
  'id-match': IdMatch;
  'implicit-arrow-linebreak': ImplicitArrowLinebreak;
  indent: Indent;
  'init-declarations': InitDeclarations;
  'jsx-quotes': JsxQuotes;
  'key-spacing': KeySpacing;
  'keyword-spacing': KeywordSpacing;
  'line-comment-position': LineCommentPosition;
  'linebreak-style': LinebreakStyle;
  'lines-around-comment': LinesAroundComment;
  'lines-between-class-members': LinesBetweenClassMembers;
  'logical-assignment-operators': LogicalAssignmentOperators;
  'max-classes-per-file': MaxClassesPerFile;
  'max-depth': MaxDepth;
  'max-len': MaxLen;
  'max-lines': MaxLines;
  'max-lines-per-function': MaxLinesPerFunction;
  'max-nested-callbacks': MaxNestedCallbacks;
  'max-params': MaxParams;
  'max-statements': MaxStatements;
  'max-statements-per-line': MaxStatementsPerLine;
  'multiline-comment-style': MultilineCommentStyle;
  'multiline-ternary': MultilineTernary;
  'new-cap': NewCap;
  'new-parens': NewParens;
  'newline-per-chained-call': NewlinePerChainedCall;
  'no-alert': NoAlert;
  'no-array-constructor': NoArrayConstructor;
  'no-async-promise-executor': NoAsyncPromiseExecutor;
  'no-await-in-loop': NoAwaitInLoop;
  'no-bitwise': NoBitwise;
  'no-caller': NoCaller;
  'no-case-declarations': NoCaseDeclarations;
  'no-class-assign': NoClassAssign;
  'no-compare-neg-zero': NoCompareNegZero;
  'no-cond-assign': NoCondAssign;
  'no-confusing-arrow': NoConfusingArrow;
  'no-console': NoConsole;
  'no-const-assign': NoConstAssign;
  'no-constant-binary-expression': NoConstantBinaryExpression;
  'no-constant-condition': NoConstantCondition;
  'no-constructor-return': NoConstructorReturn;
  'no-continue': NoContinue;
  'no-control-regex': NoControlRegex;
  'no-debugger': NoDebugger;
  'no-delete-var': NoDeleteVar;
  'no-div-regex': NoDivRegex;
  'no-dupe-args': NoDupeArgs;
  'no-dupe-class-members': NoDupeClassMembers;
  'no-dupe-else-if': NoDupeElseIf;
  'no-dupe-keys': NoDupeKeys;
  'no-duplicate-case': NoDuplicateCase;
  'no-duplicate-imports': NoDuplicateImports;
  'no-else-return': NoElseReturn;
  'no-empty': NoEmpty;
  'no-empty-character-class': NoEmptyCharacterClass;
  'no-empty-function': NoEmptyFunction;
  'no-empty-pattern': NoEmptyPattern;
  'no-empty-static-block': NoEmptyStaticBlock;
  'no-eq-null': NoEqNull;
  'no-eval': NoEval;
  'no-ex-assign': NoExAssign;
  'no-extend-native': NoExtendNative;
  'no-extra-bind': NoExtraBind;
  'no-extra-boolean-cast': NoExtraBooleanCast;
  'no-extra-label': NoExtraLabel;
  'no-extra-parens': NoExtraParens;
  'no-extra-semi': NoExtraSemi;
  'no-fallthrough': NoFallthrough;
  'no-floating-decimal': NoFloatingDecimal;
  'no-func-assign': NoFuncAssign;
  'no-global-assign': NoGlobalAssign;
  'no-implicit-coercion': NoImplicitCoercion;
  'no-implicit-globals': NoImplicitGlobals;
  'no-implied-eval': NoImpliedEval;
  'no-import-assign': NoImportAssign;
  'no-inline-comments': NoInlineComments;
  'no-inner-declarations': NoInnerDeclarations;
  'no-invalid-regexp': NoInvalidRegexp;
  'no-invalid-this': NoInvalidThis;
  'no-irregular-whitespace': NoIrregularWhitespace;
  'no-iterator': NoIterator;
  'no-label-var': NoLabelVar;
  'no-labels': NoLabels;
  'no-lone-blocks': NoLoneBlocks;
  'no-lonely-if': NoLonelyIf;
  'no-loop-func': NoLoopFunc;
  'no-loss-of-precision': NoLossOfPrecision;
  'no-magic-numbers': NoMagicNumbers;
  'no-misleading-character-class': NoMisleadingCharacterClass;
  'no-mixed-operators': NoMixedOperators;
  'no-mixed-spaces-and-tabs': NoMixedSpacesAndTabs;
  'no-multi-assign': NoMultiAssign;
  'no-multi-spaces': NoMultiSpaces;
  'no-multi-str': NoMultiStr;
  'no-multiple-empty-lines': NoMultipleEmptyLines;
  'no-negated-condition': NoNegatedCondition;
  'no-nested-ternary': NoNestedTernary;
  'no-new': NoNew;
  'no-new-func': NoNewFunc;
  'no-new-native-nonconstructor': NoNewNativeNonconstructor;
  'no-new-object': NoNewObject;
  'no-new-symbol': NoNewSymbol;
  'no-new-wrappers': NoNewWrappers;
  'no-nonoctal-decimal-escape': NoNonoctalDecimalEscape;
  'no-obj-calls': NoObjCalls;
  'no-octal': NoOctal;
  'no-octal-escape': NoOctalEscape;
  'no-param-reassign': NoParamReassign;
  'no-plusplus': NoPlusplus;
  'no-promise-executor-return': NoPromiseExecutorReturn;
  'no-proto': NoProto;
  'no-prototype-builtins': NoPrototypeBuiltins;
  'no-redeclare': NoRedeclare;
  'no-regex-spaces': NoRegexSpaces;
  'no-restricted-exports': NoRestrictedExports;
  'no-restricted-globals': NoRestrictedGlobals;
  'no-restricted-imports': NoRestrictedImports;
  'no-restricted-properties': NoRestrictedProperties;
  'no-restricted-syntax': NoRestrictedSyntax;
  'no-return-assign': NoReturnAssign;
  'no-return-await': NoReturnAwait;
  'no-script-url': NoScriptUrl;
  'no-self-assign': NoSelfAssign;
  'no-self-compare': NoSelfCompare;
  'no-sequences': NoSequences;
  'no-setter-return': NoSetterReturn;
  'no-shadow': NoShadow;
  'no-shadow-restricted-names': NoShadowRestrictedNames;
  'no-sparse-arrays': NoSparseArrays;
  'no-tabs': NoTabs;
  'no-template-curly-in-string': NoTemplateCurlyInString;
  'no-ternary': NoTernary;
  'no-this-before-super': NoThisBeforeSuper;
  'no-throw-literal': NoThrowLiteral;
  'no-trailing-spaces': NoTrailingSpaces;
  'no-undef': NoUndef;
  'no-undef-init': NoUndefInit;
  'no-undefined': NoUndefined;
  'no-underscore-dangle': NoUnderscoreDangle;
  'no-unexpected-multiline': NoUnexpectedMultiline;
  'no-unmodified-loop-condition': NoUnmodifiedLoopCondition;
  'no-unneeded-ternary': NoUnneededTernary;
  'no-unreachable': NoUnreachable;
  'no-unreachable-loop': NoUnreachableLoop;
  'no-unsafe-finally': NoUnsafeFinally;
  'no-unsafe-negation': NoUnsafeNegation;
  'no-unsafe-optional-chaining': NoUnsafeOptionalChaining;
  'no-unused-expressions': NoUnusedExpressions;
  'no-unused-labels': NoUnusedLabels;
  'no-unused-private-class-members': NoUnusedPrivateClassMembers;
  'no-unused-vars': NoUnusedVars;
  'no-use-before-define': NoUseBeforeDefine;
  'no-useless-backreference': NoUselessBackreference;
  'no-useless-call': NoUselessCall;
  'no-useless-catch': NoUselessCatch;
  'no-useless-computed-key': NoUselessComputedKey;
  'no-useless-concat': NoUselessConcat;
  'no-useless-constructor': NoUselessConstructor;
  'no-useless-escape': NoUselessEscape;
  'no-useless-rename': NoUselessRename;
  'no-useless-return': NoUselessReturn;
  'no-var': NoVar;
  'no-void': NoVoid;
  'no-warning-comments': NoWarningComments;
  'no-whitespace-before-property': NoWhitespaceBeforeProperty;
  'no-with': NoWith;
  'nonblock-statement-body-position': NonblockStatementBodyPosition;
  'object-curly-newline': ObjectCurlyNewline;
  'object-curly-spacing': ObjectCurlySpacing;
  'object-property-newline': ObjectPropertyNewline;
  'object-shorthand': ObjectShorthand;
  'one-var': OneVar;
  'one-var-declaration-per-line': OneVarDeclarationPerLine;
  'operator-assignment': OperatorAssignment;
  'operator-linebreak': OperatorLinebreak;
  'padded-blocks': PaddedBlocks;
  'padding-line-between-statements': PaddingLineBetweenStatements;
  'prefer-arrow-callback': PreferArrowCallback;
  'prefer-const': PreferConst;
  'prefer-destructuring': PreferDestructuring;
  'prefer-exponentiation-operator': PreferExponentiationOperator;
  'prefer-named-capture-group': PreferNamedCaptureGroup;
  'prefer-numeric-literals': PreferNumericLiterals;
  'prefer-object-has-own': PreferObjectHasOwn;
  'prefer-object-spread': PreferObjectSpread;
  'prefer-promise-reject-errors': PreferPromiseRejectErrors;
  'prefer-regex-literals': PreferRegexLiterals;
  'prefer-rest-params': PreferRestParams;
  'prefer-spread': PreferSpread;
  'prefer-template': PreferTemplate;
  'quote-props': QuoteProps;
  quotes: Quotes;
  radix: Radix;
  'require-atomic-updates': RequireAtomicUpdates;
  'require-await': RequireAwait;
  'require-unicode-regexp': RequireUnicodeRegexp;
  'require-yield': RequireYield;
  'rest-spread-spacing': RestSpreadSpacing;
  semi: Semi;
  'semi-spacing': SemiSpacing;
  'semi-style': SemiStyle;
  'sort-imports': SortImports;
  'sort-keys': SortKeys;
  'sort-vars': SortVars;
  'space-before-blocks': SpaceBeforeBlocks;
  'space-before-function-paren': SpaceBeforeFunctionParen;
  'space-in-parens': SpaceInParens;
  'space-infix-ops': SpaceInfixOps;
  'space-unary-ops': SpaceUnaryOps;
  'spaced-comment': SpacedComment;
  strict: Strict;
  'switch-colon-spacing': SwitchColonSpacing;
  'symbol-description': SymbolDescription;
  'template-curly-spacing': TemplateCurlySpacing;
  'template-tag-spacing': TemplateTagSpacing;
  'unicode-bom': UnicodeBom;
  'use-isnan': UseIsnan;
  'valid-typeof': ValidTypeof;
  'vars-on-top': VarsOnTop;
  'wrap-iife': WrapIife;
  'wrap-regex': WrapRegex;
  'yield-star-spacing': YieldStarSpacing;
  yoda: Yoda;
}
